# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: infra-pool
  
parameters:
  - name: env
    default: 'dev'
    values:
      - dev


variables:
- name: backend
  value: mishraSPN

steps:


- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'


- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/monolithic-landing-zone/environment/${{ parameters.env }}'
    backendServiceArm: 'narayanServiceConnection'
    backendAzureRmStorageAccountName: 'mishrastorage'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'monolithic.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/monolithic-landing-zone/environment/${{ parameters.env }}'
    environmentServiceNameAzureRM: 'narayanServiceConnection'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/monolithic-landing-zone/environment/${{ parameters.env }}'
    environmentServiceNameAzureRM: 'narayanServiceConnection'




